version: "3"

services:
  hercules:
    container_name: hercules
    image: moviedomfo/person_express 
    ports:
      - 3025:3016
    environment:
      - SERVER_NAME="hercules comerce ${PORT}"
    volumes:
      - /e/volumens/express/orders:/app/files
    networks:
      net_eco:
        ipv4_address: 172.20.0.3



# networking for the Redis container
networks:
  net_eco:
    ipam:
      #driver: default
      config:
        - subnet: 172.20.0.0/16
